import { DefaultTheme } from 'react-native-paper';

export const colors = {
    primary: '#1E3A8A',
    secondary: '#3B82F6',
    accent: '#10B981',
    background: '#F3F4F6',
    surface: '#FFFFFF',
    error: '#EF4444',
    text: '#111827',
    textSecondary: '#6B7280',
    border: '#E5E7EB',
    success: '#10B981',
    warning: '#F59E0B',
    info: '#3B82F6',
};

export const theme = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
        primary: colors.primary,
        secondary: colors.secondary,
        accent: colors.accent,
        background: colors.background,
        surface: colors.surface,
        error: colors.error,
        text: colors.text,
        placeholder: colors.textSecondary,
        backdrop: 'rgba(0, 0, 0, 0.5)',
    },
    fonts: {
        ...DefaultTheme.fonts,
        regular: {
            fontFamily: 'Poppins-Regular',
            fontWeight: 'normal',
        },
        medium: {
            fontFamily: 'Poppins-SemiBold',
            fontWeight: '600',
        },
        light: {
            fontFamily: 'Poppins-Regular',
            fontWeight: '300',
        },
        thin: {
            fontFamily: 'Poppins-Regular',
            fontWeight: '100',
        },
        // Add these additional variants that React Native Paper expects
        labelSmall: {
            fontFamily: 'Poppins-Regular',
            fontSize: 11,
            fontWeight: '500',
            letterSpacing: 0.5,
            lineHeight: 16,
        },
        labelMedium: {
            fontFamily: 'Poppins-Regular',
            fontSize: 12,
            fontWeight: '500',
            letterSpacing: 0.5,
            lineHeight: 16,
        },
        labelLarge: {
            fontFamily: 'Poppins-SemiBold',
            fontSize: 14,
            fontWeight: '500',
            letterSpacing: 0.1,
            lineHeight: 20,
        },
        bodySmall: {
            fontFamily: 'Poppins-Regular',
            fontSize: 12,
            fontWeight: '400',
            letterSpacing: 0.4,
            lineHeight: 16,
        },
        bodyMedium: {
            fontFamily: 'Poppins-Regular',
            fontSize: 14,
            fontWeight: '400',
            letterSpacing: 0.25,
            lineHeight: 20,
        },
        bodyLarge: {
            fontFamily: 'Poppins-Regular',
            fontSize: 16,
            fontWeight: '400',
            letterSpacing: 0.15,
            lineHeight: 24,
        },
        headlineSmall: {
            fontFamily: 'Poppins-Regular',
            fontSize: 24,
            fontWeight: '400',
            letterSpacing: 0,
            lineHeight: 32,
        },
        headlineMedium: {
            fontFamily: 'Poppins-Regular',
            fontSize: 28,
            fontWeight: '400',
            letterSpacing: 0,
            lineHeight: 36,
        },
        headlineLarge: {
            fontFamily: 'Poppins-Regular',
            fontSize: 32,
            fontWeight: '400',
            letterSpacing: 0,
            lineHeight: 40,
        },
        displaySmall: {
            fontFamily: 'Poppins-Regular',
            fontSize: 36,
            fontWeight: '400',
            letterSpacing: 0,
            lineHeight: 44,
        },
        displayMedium: {
            fontFamily: 'Poppins-Regular',
            fontSize: 45,
            fontWeight: '400',
            letterSpacing: 0,
            lineHeight: 52,
        },
        displayLarge: {
            fontFamily: 'Poppins-Regular',
            fontSize: 57,
            fontWeight: '400',
            letterSpacing: 0,
            lineHeight: 64,
        },
        titleSmall: {
            fontFamily: 'Poppins-SemiBold',
            fontSize: 14,
            fontWeight: '500',
            letterSpacing: 0.1,
            lineHeight: 20,
        },
        titleMedium: {
            fontFamily: 'Poppins-SemiBold',
            fontSize: 16,
            fontWeight: '500',
            letterSpacing: 0.15,
            lineHeight: 24,
        },
        titleLarge: {
            fontFamily: 'Poppins-SemiBold',
            fontSize: 22,
            fontWeight: '500',
            letterSpacing: 0,
            lineHeight: 28,
        },
    },
};